---
- name: playbook for vlan
  hosts: all

  tasks:
    - name: Show interface config
      junipernetworks.junos.junos_command:
        commands: show configuration interfaces | display set
      register: out
    - ansible.builtin.debug:
        var: out.stdout_lines