---
- name: test
  hosts: juniper
  gather_facts: false

  tasks:
    - name: ping host
      junipernetworks.junos.junos_ping:
        dest: "{{ dest_ip }}"
        size: 1024
        ttl: 128
      register: result
    
    - name: Print result of ping
      debug:
        var: result