---
-
  hosts: all
  gather_facts: false

  tasks:
    - name: Fetch running configuration of device
      cisco.ios.ios_command:
        commands: show run
      register: result

    - name: Print the running configuration on the device
      debug:
        msg: "{{ result }}"
