---
-
  hosts: all
  gather_facts: false

  tasks:
    - name: set NTP server
      cisco.ios.ios_config:
        lines:
          - ntp server "{{ ntp_server }}"
    - name: Fetch ntp server 
      cisco.ios.ios_command:
        commands: show run | include ntp server 
      register: result

    - name: Print the running configuration on the device
      debug:
        msg: "{{ result }}"
