---
- name: playbook for vlan
  hosts: switches
  gather_facts: false

  tasks:
    - name: Configure VLANs
      junipernetworks.junos.junos_vlans:
        config:
          - name: "{{ item.name }}"
            vlan_id: "{{ item.id }}"
        state: merged
      loop: "{{ VLANS }}"

    - name: Remove factory inet from switch ports
      junipernetworks.junos.junos_config:
        lines:
          - "delete interfaces {{ item }} unit 0 family inet"
      loop: "{{ ['xe-0/0/0'] + (VLANS | map(attribute='interface') | list) }}"

    - name: Configure trunk port
      junipernetworks.junos.junos_l2_interfaces:
        config:
          - name: xe-0/0/0
            trunk:
              native_vlan: 99
              allowed_vlans: "{{ VLANS | map(attribute='id') | map('string') | list }}"
        state: merged

    - name: Configure access ports
      junipernetworks.junos.junos_l2_interfaces:
        config:
          - name: "{{ item.interface }}"
            enhanced_layer: true
            access:
              vlan: "{{ item.name }}"
        state: merged
      loop: "{{ VLANS }}"

    - name: Fetch VLAN configuration
      junipernetworks.junos.junos_command:
        commands:
          - show vlans
      register: vlan_result

    - name: Print VLAN result
      ansible.builtin.debug:
        var: vlan_result.stdout_lines
